### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by muralikodali** [mensinda/qScan#1]
following command produces an error shown below.

```
meson compile -C build
```

```
FAILED: gui/qScan.p/config_QScanConfig.cpp.o
c++ -Igui/qScan.p -Igui -I../gui -I../gui/widgets -I../gui/viewer -Ilib -I../lib -I../subprojects/spdlog-1.11.0/include -Isubprojects/spdlog-1.11.0/__CMake_build -I../subprojects/spdlog-1.11.0/__CMake_build -Isubprojects/spdlog-1.11.0 -I../subprojects/spdlog-1.11.0 -I/usr/include/ImageMagick-7 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++20 -O2 -g -Wno-pedantic -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DSPDLOG_COMPILED_LIB -DQT_WIDGETS_LIB -isystem/usr/include/qt/QtWidgets -DQT_GUI_LIB -isystem/usr/include/qt/QtGui -DQT_CORE_LIB -isystem/usr/include/qt/QtCore -isystem/usr/include/qt -fPIC -MD -MQ gui/qScan.p/config_QScanConfig.cpp.o -MF gui/qScan.p/config_QScanConfig.cpp.o.d -o gui/qScan.p/config_QScanConfig.cpp.o -c ../gui/config/QScanConfig.cpp
../gui/config/QScanConfig.cpp:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
```

**Comment by eli-schwartz** [comment]
Seems like a simple bug -- `json_dep` is looked up but never added to any targets, so it should be added to gui/qscan.

It probably slipped by, because if the dependency is installed to the standard system includedir, the compiler sees the header by default without adding any additional includes.

**Comment by mensinda** [comment]
Thanks, should be fixed now.

**Comment by muralikodali** [comment]
loading the scanner fails as shown below : 

my scanner is Canon LIDE 2020 flatbed

![screenshot_20221226193514](https://user-images.githubusercontent.com/11482766/209557049-5f487f8d-3a83-42c2-9709-5443c61c30a0.png)

there is no issue for connecting with scanner using software like xsane or vuescan

**Comment by mensinda** [comment]
@muralikodali Should hopefully be fixed now, but please open a new issue next time since this error is unrelated to your first problem.
